#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/sanders

PRODUCT_COPY_FILES += \
    vendor/motorola/sanders/proprietary/vendor/lib/modules/isdbt.ko:$(TARGET_COPY_OUT_VENDOR)/lib/modules/isdbt.ko \
    vendor/motorola/sanders/proprietary/product/lib64/libdtvhal.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libdtvhal.so \
    vendor/motorola/sanders/proprietary/product/lib64/libdtvtuner.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libdtvtuner.so \
    vendor/motorola/sanders/proprietary/product/etc/permissions/sku_XT1802/mot_dtv_permissions.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/sku_XT1802/mot_dtv_permissions.xml \
    vendor/motorola/sanders/proprietary/product/etc/permissions/sku_XT1802/com.motorola.hardware.dtv.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/sku_XT1802/com.motorola.hardware.dtv.xml \
    vendor/motorola/sanders/proprietary/product/etc/permissions/telephony_product_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/telephony_product_privapp-permissions-qti.xml \
    vendor/motorola/sanders/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/motorola/sanders/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/motorola/sanders/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/motorola/sanders/proprietary/system_ext/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml \
    vendor/motorola/sanders/proprietary/system_ext/etc/permissions/telephonyservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephonyservice.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/sanders/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/motorola/sanders/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/sanders/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/sanders/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/sanders/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/sanders/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/android.hardware.gnss@2.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.1-service-qti.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/init-qcril-data.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init-qcril-data.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/init_thermal-engine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/vendor.qti.hardware.perf@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf@2.2-service.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/vendor.qti.hardware.qdutils_disp@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qdutils_disp@1.0-service-qti.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/motorola/sanders/proprietary/vendor/etc/motorola/mdmctbk/ctbk_cfg.xml:$(TARGET_COPY_OUT_VENDOR)/etc/motorola/mdmctbk/ctbk_cfg.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_djn_1080p_550.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_djn_1080p_550.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tianma_1080p_550.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tianma_1080p_550.xml \
    vendor/motorola/sanders/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/motorola/sanders/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/motorola/sanders/proprietary/vendor/etc/wifi/WCNSS_qcom_wlan_nv.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_wlan_nv.bin \
    vendor/motorola/sanders/proprietary/vendor/etc/wifi/WCNSS_qcom_wlan_nv_Argentina.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_wlan_nv_Argentina.bin \
    vendor/motorola/sanders/proprietary/vendor/etc/wifi/WCNSS_qcom_wlan_nv_Brazil.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_wlan_nv_Brazil.bin \
    vendor/motorola/sanders/proprietary/vendor/etc/wifi/WCNSS_qcom_wlan_nv_India.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_wlan_nv_India.bin \
    vendor/motorola/sanders/proprietary/vendor/etc/wifi/WCNSS_qcom_wlan_nv_epa.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_wlan_nv_epa.bin \
    vendor/motorola/sanders/proprietary/vendor/etc/wifi/WCNSS_wlan_dictionary.dat:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_wlan_dictionary.dat \
    vendor/motorola/sanders/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/motorola/sanders/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/a530v1_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pfp.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/a530v1_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pm4.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/a530v2_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v2_seq.fw2 \
    vendor/motorola/sanders/proprietary/vendor/firmware/a530v3_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_gpmu.fw2 \
    vendor/motorola/sanders/proprietary/vendor/firmware/a530v3_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_seq.fw2 \
    vendor/motorola/sanders/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/motorola/sanders/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/motorola/sanders/proprietary/vendor/firmware/focaltech-biel-ft5436-06-0001-sanders.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-biel-ft5436-06-0001-sanders.bin \
    vendor/motorola/sanders/proprietary/vendor/firmware/focaltech-djn-ft5436-02-0001-sanders.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-djn-ft5436-02-0001-sanders.bin \
    vendor/motorola/sanders/proprietary/vendor/firmware/focaltech-toptouch-ft5436-0a-0001-sanders.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-toptouch-ft5436-0a-0001-sanders.bin \
    vendor/motorola/sanders/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/motorola/sanders/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/motorola/sanders/proprietary/vendor/radio/qcril_database/upgrade/10_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/10_version_update_ecc_table.sql \
    vendor/motorola/sanders/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/motorola/sanders/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/motorola/sanders/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/motorola/sanders/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/motorola/sanders/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    vendor/motorola/sanders/proprietary/vendor/radio/qcril_database/upgrade/6_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    vendor/motorola/sanders/proprietary/vendor/radio/qcril_database/upgrade/7_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql \
    vendor/motorola/sanders/proprietary/vendor/radio/qcril_database/upgrade/8_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/8_version_update_ecc_table.sql \
    vendor/motorola/sanders/proprietary/vendor/radio/qcril_database/upgrade/9_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/9_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    libGLESv2_adreno \
    libOpenCL \
    libQSEEComAPI \
    libadreno_utils \
    libdiag \
    libfastcvopt \
    libgsl \
    libllvm-glnext \
    libqmi_cci \
    libqmi_common_so \
    libqmi_encdec \
    libsensor1 \
    com.fingerprints.extension@1.0_vendor \
    camera.msm8953 \
    lib_mot_app6_metadata \
    lib_mot_led_calibration \
    lib_motsensorlistener \
    libactuator_dw9718s \
    libactuator_dw9763 \
    libactuator_dw9767 \
    libactuator_lc898217xc \
    libactuator_mot_ak7371 \
    libactuator_mot_ak7371_bear \
    libactuator_mot_ak7371_mono \
    libactuator_pseudo \
    libchromaflash \
    libchromatix_ar1335_common \
    libchromatix_ar1335_cpp_hfr_120 \
    libchromatix_ar1335_cpp_liveshot \
    libchromatix_ar1335_cpp_preview \
    libchromatix_ar1335_cpp_snapshot \
    libchromatix_ar1335_cpp_video \
    libchromatix_ar1335_default_video \
    libchromatix_ar1335_hfr_120 \
    libchromatix_ar1335_hfr_120_3a \
    libchromatix_ar1335_postproc \
    libchromatix_ar1335_snapshot \
    libchromatix_ar1335_zsl_preview_3a \
    libchromatix_ar1335_zsl_video_3a \
    libchromatix_imx219_common \
    libchromatix_imx219_cpp_hfr_120 \
    libchromatix_imx219_cpp_liveshot \
    libchromatix_imx219_cpp_preview \
    libchromatix_imx219_cpp_snapshot \
    libchromatix_imx219_cpp_video_full \
    libchromatix_imx219_hfr_120 \
    libchromatix_imx219_hfr_120_3a \
    libchromatix_imx219_postproc \
    libchromatix_imx219_snapshot \
    libchromatix_imx219_video_full \
    libchromatix_imx219_zsl_preview_3a \
    libchromatix_imx219_zsl_video_3a \
    libchromatix_imx338_4k_ihdr_video_3a \
    libchromatix_imx338_4k_video_3a \
    libchromatix_imx338_common \
    libchromatix_imx338_cpp_hfr_120 \
    libchromatix_imx338_cpp_hfr_60 \
    libchromatix_imx338_cpp_ihdr_video \
    libchromatix_imx338_cpp_ihdr_video_4k \
    libchromatix_imx338_cpp_liveshot \
    libchromatix_imx338_cpp_liveshot_4k \
    libchromatix_imx338_cpp_liveshot_4k_ihdr \
    libchromatix_imx338_cpp_liveshot_ihdr \
    libchromatix_imx338_cpp_qtr_res_snapshot \
    libchromatix_imx338_cpp_snapshot \
    libchromatix_imx338_cpp_video \
    libchromatix_imx338_cpp_video_4k \
    libchromatix_imx338_default_ihdr_video \
    libchromatix_imx338_default_video \
    libchromatix_imx338_hfr_120 \
    libchromatix_imx338_hfr_120_3a \
    libchromatix_imx338_hfr_60 \
    libchromatix_imx338_hfr_60_3a \
    libchromatix_imx338_ihdr_video_3a \
    libchromatix_imx338_ihdr_video_4k \
    libchromatix_imx338_postproc \
    libchromatix_imx338_qtr_res_preview_3a \
    libchromatix_imx338_qtr_res_snapshot \
    libchromatix_imx338_snapshot \
    libchromatix_imx338_video_4k \
    libchromatix_imx338_zsl_preview_3a \
    libchromatix_imx338_zsl_video_3a \
    libchromatix_mot_imx214_4k_ihdr_video_3A \
    libchromatix_mot_imx214_4k_video_3A \
    libchromatix_mot_imx214_common \
    libchromatix_mot_imx214_cpp_hfr_120 \
    libchromatix_mot_imx214_cpp_hfr_60 \
    libchromatix_mot_imx214_cpp_liveshot \
    libchromatix_mot_imx214_cpp_liveshot_4k \
    libchromatix_mot_imx214_cpp_liveshot_4k_ihdr \
    libchromatix_mot_imx214_cpp_liveshot_ihdr \
    libchromatix_mot_imx214_cpp_snapshot \
    libchromatix_mot_imx214_cpp_video \
    libchromatix_mot_imx214_cpp_video_4k \
    libchromatix_mot_imx214_cpp_video_4k_ihdr \
    libchromatix_mot_imx214_cpp_video_ihdr \
    libchromatix_mot_imx214_default_4k_video \
    libchromatix_mot_imx214_default_ihdr_video \
    libchromatix_mot_imx214_default_ihdr_video_4k \
    libchromatix_mot_imx214_default_video \
    libchromatix_mot_imx214_hfr_120 \
    libchromatix_mot_imx214_hfr_120_3A \
    libchromatix_mot_imx214_hfr_60 \
    libchromatix_mot_imx214_hfr_60_3A \
    libchromatix_mot_imx214_ihdr_video_3A \
    libchromatix_mot_imx214_postproc \
    libchromatix_mot_imx214_snapshot \
    libchromatix_mot_imx214_zsl_preview_3A \
    libchromatix_mot_imx214_zsl_video_3A \
    libchromatix_mot_imx258_bear_4k_preview_3a \
    libchromatix_mot_imx258_bear_4k_video_3a \
    libchromatix_mot_imx258_bear_common \
    libchromatix_mot_imx258_bear_cpp_hfr_120 \
    libchromatix_mot_imx258_bear_cpp_hfr_60 \
    libchromatix_mot_imx258_bear_cpp_liveshot \
    libchromatix_mot_imx258_bear_cpp_preview \
    libchromatix_mot_imx258_bear_cpp_snapshot \
    libchromatix_mot_imx258_bear_cpp_video \
    libchromatix_mot_imx258_bear_default_video \
    libchromatix_mot_imx258_bear_hfr_120 \
    libchromatix_mot_imx258_bear_hfr_120_3a \
    libchromatix_mot_imx258_bear_hfr_60 \
    libchromatix_mot_imx258_bear_hfr_60_3a \
    libchromatix_mot_imx258_bear_postproc \
    libchromatix_mot_imx258_bear_preview \
    libchromatix_mot_imx258_bear_snapshot \
    libchromatix_mot_imx258_bear_zsl_preview_3a \
    libchromatix_mot_imx258_bear_zsl_video_3a \
    libchromatix_mot_imx258_common \
    libchromatix_mot_imx258_cpp_hfr_120 \
    libchromatix_mot_imx258_cpp_liveshot \
    libchromatix_mot_imx258_cpp_preview \
    libchromatix_mot_imx258_cpp_snapshot \
    libchromatix_mot_imx258_cpp_video \
    libchromatix_mot_imx258_default_video \
    libchromatix_mot_imx258_hfr_120 \
    libchromatix_mot_imx258_hfr_120_3a \
    libchromatix_mot_imx258_ihdr_video \
    libchromatix_mot_imx258_ihdr_video_3a \
    libchromatix_mot_imx258_mono_4k_preview_3a \
    libchromatix_mot_imx258_mono_4k_video_3a \
    libchromatix_mot_imx258_mono_common \
    libchromatix_mot_imx258_mono_cpp_hfr_120 \
    libchromatix_mot_imx258_mono_cpp_hfr_60 \
    libchromatix_mot_imx258_mono_cpp_liveshot \
    libchromatix_mot_imx258_mono_cpp_preview \
    libchromatix_mot_imx258_mono_cpp_snapshot \
    libchromatix_mot_imx258_mono_cpp_video \
    libchromatix_mot_imx258_mono_default_video \
    libchromatix_mot_imx258_mono_hfr_120 \
    libchromatix_mot_imx258_mono_hfr_120_3a \
    libchromatix_mot_imx258_mono_hfr_60 \
    libchromatix_mot_imx258_mono_hfr_60_3a \
    libchromatix_mot_imx258_mono_postproc \
    libchromatix_mot_imx258_mono_preview \
    libchromatix_mot_imx258_mono_snapshot \
    libchromatix_mot_imx258_mono_zsl_preview_3a \
    libchromatix_mot_imx258_mono_zsl_video_3a \
    libchromatix_mot_imx258_postproc \
    libchromatix_mot_imx258_snapshot \
    libchromatix_mot_imx258_zsl_preview_3a \
    libchromatix_mot_imx258_zsl_video_3a \
    libchromatix_mot_imx362_1080p_preview_3a \
    libchromatix_mot_imx362_1080p_video_3a \
    libchromatix_mot_imx362_4k_ihdr_video_3a \
    libchromatix_mot_imx362_4k_preview_3a \
    libchromatix_mot_imx362_4k_video_3a \
    libchromatix_mot_imx362_common \
    libchromatix_mot_imx362_cpp_hfr_120 \
    libchromatix_mot_imx362_cpp_hfr_240 \
    libchromatix_mot_imx362_cpp_hfr_60 \
    libchromatix_mot_imx362_cpp_liveshot \
    libchromatix_mot_imx362_cpp_preview \
    libchromatix_mot_imx362_cpp_snapshot \
    libchromatix_mot_imx362_cpp_video \
    libchromatix_mot_imx362_cpp_video_4k \
    libchromatix_mot_imx362_default_preview_3a \
    libchromatix_mot_imx362_default_video \
    libchromatix_mot_imx362_default_video_3a \
    libchromatix_mot_imx362_fullsize_preview_3a \
    libchromatix_mot_imx362_fullsize_video_3a \
    libchromatix_mot_imx362_hfr_120 \
    libchromatix_mot_imx362_hfr_120_3a \
    libchromatix_mot_imx362_hfr_240 \
    libchromatix_mot_imx362_hfr_240_3a \
    libchromatix_mot_imx362_hfr_60 \
    libchromatix_mot_imx362_hfr_60_3a \
    libchromatix_mot_imx362_ihdr_video \
    libchromatix_mot_imx362_ihdr_video_3a \
    libchromatix_mot_imx362_ihdr_video_4k \
    libchromatix_mot_imx362_postproc \
    libchromatix_mot_imx362_preview \
    libchromatix_mot_imx362_snapshot \
    libchromatix_mot_imx362_video_4k \
    libchromatix_mot_ov5695_common \
    libchromatix_mot_ov5695_cpp_hfr_120 \
    libchromatix_mot_ov5695_cpp_liveshot \
    libchromatix_mot_ov5695_cpp_snapshot \
    libchromatix_mot_ov5695_cpp_video \
    libchromatix_mot_ov5695_default_video \
    libchromatix_mot_ov5695_default_video_3a \
    libchromatix_mot_ov5695_hfr_120 \
    libchromatix_mot_ov5695_hfr_120_3a \
    libchromatix_mot_ov5695_ofilm_common \
    libchromatix_mot_ov5695_ofilm_cpp_hfr_120 \
    libchromatix_mot_ov5695_ofilm_cpp_liveshot \
    libchromatix_mot_ov5695_ofilm_cpp_snapshot \
    libchromatix_mot_ov5695_ofilm_cpp_video \
    libchromatix_mot_ov5695_ofilm_default_video \
    libchromatix_mot_ov5695_ofilm_default_video_3a \
    libchromatix_mot_ov5695_ofilm_hfr_120 \
    libchromatix_mot_ov5695_ofilm_hfr_120_3a \
    libchromatix_mot_ov5695_ofilm_postproc \
    libchromatix_mot_ov5695_ofilm_snapshot \
    libchromatix_mot_ov5695_ofilm_snapshot_3a \
    libchromatix_mot_ov5695_postproc \
    libchromatix_mot_ov5695_snapshot \
    libchromatix_mot_ov5695_snapshot_3a \
    libchromatix_mot_s5k2l7_1080p_preview_3a \
    libchromatix_mot_s5k2l7_1080p_video_3a \
    libchromatix_mot_s5k2l7_4k_ihdr_video_3a \
    libchromatix_mot_s5k2l7_4k_preview_3a \
    libchromatix_mot_s5k2l7_4k_video_3a \
    libchromatix_mot_s5k2l7_common \
    libchromatix_mot_s5k2l7_cpp_hfr_120 \
    libchromatix_mot_s5k2l7_cpp_hfr_240 \
    libchromatix_mot_s5k2l7_cpp_hfr_60 \
    libchromatix_mot_s5k2l7_cpp_liveshot \
    libchromatix_mot_s5k2l7_cpp_preview \
    libchromatix_mot_s5k2l7_cpp_snapshot \
    libchromatix_mot_s5k2l7_cpp_video \
    libchromatix_mot_s5k2l7_cpp_video_4k \
    libchromatix_mot_s5k2l7_default_preview_3a \
    libchromatix_mot_s5k2l7_default_video \
    libchromatix_mot_s5k2l7_default_video_3a \
    libchromatix_mot_s5k2l7_fullsize_preview_3a \
    libchromatix_mot_s5k2l7_fullsize_video_3a \
    libchromatix_mot_s5k2l7_hfr_120 \
    libchromatix_mot_s5k2l7_hfr_120_3a \
    libchromatix_mot_s5k2l7_hfr_240 \
    libchromatix_mot_s5k2l7_hfr_240_3a \
    libchromatix_mot_s5k2l7_hfr_60 \
    libchromatix_mot_s5k2l7_hfr_60_3a \
    libchromatix_mot_s5k2l7_ihdr_video \
    libchromatix_mot_s5k2l7_ihdr_video_3a \
    libchromatix_mot_s5k2l7_ihdr_video_4k \
    libchromatix_mot_s5k2l7_postproc \
    libchromatix_mot_s5k2l7_preview \
    libchromatix_mot_s5k2l7_snapshot \
    libchromatix_mot_s5k2l7_video_4k \
    libchromatix_mot_s5k2l7sa_1080p_preview_3a \
    libchromatix_mot_s5k2l7sa_1080p_video_3a \
    libchromatix_mot_s5k2l7sa_4k_ihdr_video_3a \
    libchromatix_mot_s5k2l7sa_4k_preview_3a \
    libchromatix_mot_s5k2l7sa_4k_video_3a \
    libchromatix_mot_s5k2l7sa_common \
    libchromatix_mot_s5k2l7sa_cpp_hfr_120 \
    libchromatix_mot_s5k2l7sa_cpp_hfr_240 \
    libchromatix_mot_s5k2l7sa_cpp_hfr_60 \
    libchromatix_mot_s5k2l7sa_cpp_liveshot \
    libchromatix_mot_s5k2l7sa_cpp_preview \
    libchromatix_mot_s5k2l7sa_cpp_snapshot \
    libchromatix_mot_s5k2l7sa_cpp_video \
    libchromatix_mot_s5k2l7sa_cpp_video_4k \
    libchromatix_mot_s5k2l7sa_default_preview_3a \
    libchromatix_mot_s5k2l7sa_default_video \
    libchromatix_mot_s5k2l7sa_default_video_3a \
    libchromatix_mot_s5k2l7sa_fullsize_preview_3a \
    libchromatix_mot_s5k2l7sa_fullsize_video_3a \
    libchromatix_mot_s5k2l7sa_hfr_120 \
    libchromatix_mot_s5k2l7sa_hfr_120_3a \
    libchromatix_mot_s5k2l7sa_hfr_240 \
    libchromatix_mot_s5k2l7sa_hfr_240_3a \
    libchromatix_mot_s5k2l7sa_hfr_60 \
    libchromatix_mot_s5k2l7sa_hfr_60_3a \
    libchromatix_mot_s5k2l7sa_ihdr_video \
    libchromatix_mot_s5k2l7sa_ihdr_video_3a \
    libchromatix_mot_s5k2l7sa_ihdr_video_4k \
    libchromatix_mot_s5k2l7sa_postproc \
    libchromatix_mot_s5k2l7sa_preview \
    libchromatix_mot_s5k2l7sa_snapshot \
    libchromatix_mot_s5k2l7sa_video_4k \
    libchromatix_mot_s5k3l8_bear_common \
    libchromatix_mot_s5k3l8_bear_cpp_hfr_120 \
    libchromatix_mot_s5k3l8_bear_cpp_hfr_60 \
    libchromatix_mot_s5k3l8_bear_cpp_liveshot \
    libchromatix_mot_s5k3l8_bear_cpp_preview \
    libchromatix_mot_s5k3l8_bear_cpp_snapshot \
    libchromatix_mot_s5k3l8_bear_cpp_snapshot_custom \
    libchromatix_mot_s5k3l8_bear_cpp_snapshot_downscale \
    libchromatix_mot_s5k3l8_bear_cpp_video \
    libchromatix_mot_s5k3l8_bear_default_preview_3a \
    libchromatix_mot_s5k3l8_bear_default_video_3a \
    libchromatix_mot_s5k3l8_bear_hfr_120 \
    libchromatix_mot_s5k3l8_bear_hfr_120_3a \
    libchromatix_mot_s5k3l8_bear_hfr_60 \
    libchromatix_mot_s5k3l8_bear_hfr_60_3a \
    libchromatix_mot_s5k3l8_bear_postproc \
    libchromatix_mot_s5k3l8_bear_preview \
    libchromatix_mot_s5k3l8_bear_snapshot \
    libchromatix_mot_s5k3l8_bear_video \
    libchromatix_mot_s5k3l8_bear_zsl_preview_3a \
    libchromatix_mot_s5k3l8_bear_zsl_video_3a \
    libchromatix_mot_s5k3l8_mono_common \
    libchromatix_mot_s5k3l8_mono_cpp_hfr_120 \
    libchromatix_mot_s5k3l8_mono_cpp_liveshot \
    libchromatix_mot_s5k3l8_mono_cpp_preview \
    libchromatix_mot_s5k3l8_mono_cpp_snapshot \
    libchromatix_mot_s5k3l8_mono_cpp_snapshot_custom \
    libchromatix_mot_s5k3l8_mono_cpp_snapshot_downscale \
    libchromatix_mot_s5k3l8_mono_cpp_video \
    libchromatix_mot_s5k3l8_mono_default_preview_3a \
    libchromatix_mot_s5k3l8_mono_default_video_3a \
    libchromatix_mot_s5k3l8_mono_hfr_120 \
    libchromatix_mot_s5k3l8_mono_hfr_120_3a \
    libchromatix_mot_s5k3l8_mono_postproc \
    libchromatix_mot_s5k3l8_mono_preview \
    libchromatix_mot_s5k3l8_mono_snapshot \
    libchromatix_mot_s5k3l8_mono_video \
    libchromatix_mot_s5k3l8_mono_zsl_preview_3a \
    libchromatix_mot_s5k3l8_mono_zsl_video_3a \
    libchromatix_ov16860_4k_ihdr_video_3a \
    libchromatix_ov16860_4k_video_3a \
    libchromatix_ov16860_common \
    libchromatix_ov16860_cpp_hfr_120 \
    libchromatix_ov16860_cpp_ihdr_video \
    libchromatix_ov16860_cpp_ihdr_video_4k \
    libchromatix_ov16860_cpp_liveshot \
    libchromatix_ov16860_cpp_liveshot_4k \
    libchromatix_ov16860_cpp_liveshot_4k_ihdr \
    libchromatix_ov16860_cpp_liveshot_ihdr \
    libchromatix_ov16860_cpp_snapshot \
    libchromatix_ov16860_cpp_video \
    libchromatix_ov16860_cpp_video_4k \
    libchromatix_ov16860_default_ihdr_video \
    libchromatix_ov16860_default_video \
    libchromatix_ov16860_hfr_120 \
    libchromatix_ov16860_hfr_120_3a \
    libchromatix_ov16860_ihdr_video_3a \
    libchromatix_ov16860_ihdr_video_4k \
    libchromatix_ov16860_postproc \
    libchromatix_ov16860_snapshot \
    libchromatix_ov16860_video_4k \
    libchromatix_ov16860_zsl_preview_3a \
    libchromatix_ov16860_zsl_video_3a \
    libchromatix_ov5693_common \
    libchromatix_ov5693_cpp_hfr_120 \
    libchromatix_ov5693_cpp_liveshot \
    libchromatix_ov5693_cpp_snapshot \
    libchromatix_ov5693_cpp_video \
    libchromatix_ov5693_default_video \
    libchromatix_ov5693_default_video_3a \
    libchromatix_ov5693_hfr_120 \
    libchromatix_ov5693_hfr_120_3a \
    libchromatix_ov5693_postproc \
    libchromatix_ov5693_snapshot \
    libchromatix_ov5693_snapshot_3a \
    libchromatix_s5k3p3_common \
    libchromatix_s5k3p3_cpp_hfr_120 \
    libchromatix_s5k3p3_cpp_liveshot \
    libchromatix_s5k3p3_cpp_preview \
    libchromatix_s5k3p3_cpp_snapshot \
    libchromatix_s5k3p3_cpp_video \
    libchromatix_s5k3p3_hfr_120 \
    libchromatix_s5k3p3_hfr_120_3a \
    libchromatix_s5k3p3_ihdr_video \
    libchromatix_s5k3p3_ihdr_video_3a \
    libchromatix_s5k3p3_postproc \
    libchromatix_s5k3p3_snapshot \
    libchromatix_s5k3p3_zsl_preview_3a \
    libchromatix_s5k3p3_zsl_video_3a \
    libchromatix_s5k4h8_common \
    libchromatix_s5k4h8_cpp_hfr_120 \
    libchromatix_s5k4h8_cpp_liveshot \
    libchromatix_s5k4h8_cpp_preview \
    libchromatix_s5k4h8_cpp_snapshot \
    libchromatix_s5k4h8_cpp_snapshot_custom \
    libchromatix_s5k4h8_cpp_video_full \
    libchromatix_s5k4h8_hfr_120 \
    libchromatix_s5k4h8_hfr_120_3a \
    libchromatix_s5k4h8_postproc \
    libchromatix_s5k4h8_snapshot \
    libchromatix_s5k4h8_video_full \
    libchromatix_s5k4h8_zsl_preview_3a \
    libchromatix_s5k4h8_zsl_video_3a \
    libflash_aw3641 \
    libflash_pmic \
    libflash_sky81298 \
    libflash_wd3100 \
    libgralloc1 \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libllvd_smore \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_dcrf \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_modules \
    libmmcamera_ar1335 \
    libmmcamera_cac3_lib \
    libmmcamera_chromaflash_lib \
    libmmcamera_dbg \
    libmmcamera_dcrf_lib \
    libmmcamera_dummyalgo \
    libmmcamera_dw9763_eeprom \
    libmmcamera_dw9767_eeprom \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_gt24c64_bear_eeprom \
    libmmcamera_gt24c64_mono_eeprom \
    libmmcamera_hdr_gb_lib \
    libmmcamera_imglib \
    libmmcamera_imx219 \
    libmmcamera_imx338 \
    libmmcamera_interface \
    libmmcamera_isp_abf40 \
    libmmcamera_isp_bcc40 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats44 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc40 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct40 \
    libmmcamera_isp_color_xform_encoder40 \
    libmmcamera_isp_color_xform_viewfinder40 \
    libmmcamera_isp_cs_stats44 \
    libmmcamera_isp_demosaic40 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder40 \
    libmmcamera_isp_fovcrop_viewfinder40 \
    libmmcamera_isp_gamma40 \
    libmmcamera_isp_ihist_stats44 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff40 \
    libmmcamera_isp_rs_stats44 \
    libmmcamera_isp_scaler_encoder44 \
    libmmcamera_isp_scaler_viewfinder44 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_template \
    libmmcamera_isp_wb40 \
    libmmcamera_l4h8f20_eeprom \
    libmmcamera_llvd \
    libmmcamera_mot_imx214 \
    libmmcamera_mot_imx258 \
    libmmcamera_mot_imx258_bear \
    libmmcamera_mot_imx258_mono \
    libmmcamera_mot_imx362 \
    libmmcamera_mot_ov5695 \
    libmmcamera_mot_s5k2l7 \
    libmmcamera_mot_s5k2l7sa \
    libmmcamera_mot_s5k3l8_bear \
    libmmcamera_mot_s5k3l8_mono \
    libmmcamera_optizoom_lib \
    libmmcamera_ov5693 \
    libmmcamera_ov5693_eeprom \
    libmmcamera_ov5695_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k3p3 \
    libmmcamera_s5k3p3_eeprom \
    libmmcamera_s5k4h8 \
    libmmcamera_s5k4h8_eeprom \
    libmmcamera_sony_rumba_eeprom \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_trueportrait_lib \
    libmmcamera_ubifocus_lib \
    libmmcamera_vstab_module \
    libmmjpeg \
    libmmjpeg_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmot_afd \
    libmot_gpu_mapper \
    libmot_lux_standardization \
    libmotimager_utils \
    libmotocalibration \
    liboptizoom \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libseemore \
    libtrueportrait \
    libts_detected_face_hal \
    libts_face_beautify_hal \
    libubifocus \
    libvideoutils \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    com.qualcomm.qti.uceservice@2.3 \
    deviceInfoServiceModule \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    fm_helium \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.gnss@2.1-impl-qti \
    com.dsi.ant@1.0-impl \
    gatekeeper.msm8953 \
    keystore.msm8953 \
    vendor.qti.gnss@4.0-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.fm@1.0-impl \
    vulkan.msm8953 \
    lib-imsSDP \
    lib-rtpcommon \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsxml \
    lib-rcsconfig \
    lib-siputility \
    lib-uceservice \
    libC2D2 \
    libCB \
    libGPreqcancel \
    libGPreqcancel_svc \
    libSecureUILib \
    libStDrvInt \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadsp_default_listener \
    libadsprpc \
    libaudcal \
    libaudioalsa \
    libaudioparsers \
    libbatching \
    libbt-hidlclient \
    libbtnv \
    libc2d30_bltlib \
    libcacertclient \
    libcdfw \
    libcdfw_remote_api \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcneqmiutils \
    libconfigdb \
    libcpion \
    libdataitems \
    libdisp-aba \
    libdisplayconfig.qti \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libdsutils \
    libfastcvadsp_stub \
    libfm-hci \
    libgdtap \
    libgeofencing \
    libgnss \
    libgnsspps \
    libgps.utils \
    libhdcpsrm \
    libhdr_tm \
    libidl \
    libizat_client_api \
    libizat_core \
    liblbs_core \
    libllvm-qcom \
    libloc_api_v02 \
    libloc_core \
    libloc_socket \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblocdiagiface \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libmdmdetect \
    libmm-hdcpmgr \
    libmmosal \
    libnetmgr \
    libnetmgr_common \
    libnlnetmgr \
    liboemaids_vendor \
    liboemcrypto \
    libops \
    libpdmapper \
    libperfconfig \
    libperfgluelayer \
    libperfioctl \
    libperipheral_client \
    libqcc_file_agent \
    libqcci_legacy \
    libqcmaputils \
    libqcrilFramework \
    libqcrildatactl \
    libqdi \
    libqdp \
    libqisl \
    libqmi \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_csi \
    libqmi_legacy \
    libqmiservices \
    libqrtr \
    libqsocket \
    libqti-perfd-client-vendor \
    libqti-perfd-client \
    libqti-perfd \
    libqti-util-vendor \
    libqti-util \
    libqtigef \
    libril-qc-hal-qmi \
    libril-qc-logger \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librpmb \
    libscalar \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsecureui \
    libsecureui_svcsock \
    libsensor_reg \
    libsensorcal \
    libsoc_helper \
    libspl \
    libssd \
    libsystem_health_mon \
    libthermalclient \
    libtime_genoff \
    libtinyxml2_1 \
    libvpplibrary \
    libwms \
    libwqe \
    libwvhidl \
    libxml \
    libxtadapter \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    sensor_calibrate \
    sensors.rp \
    sensors.ssc \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.postproc@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.gnss@4.0-service \
    vendor.qti.gnss@4.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.ims@1.7 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.lpa@1.2 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.factory@1.1 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    vendor.qti.memory.pasrmanager@1.0 \
    vendor.qti.memory.pasrmanager@1.1 \
    com.qualcomm.qti.ant@1.0 \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.api@1.1 \
    com.quicinc.cne.constants@1.0 \
    com.quicinc.cne.constants@2.0 \
    com.quicinc.cne.constants@2.1 \
    libavenhancements \
    libdiag_system \
    libimscamera_jni \
    libimsmedia_jni \
    libmwqemiptablemgr \
    vendor.qti.diaghal@1.0 \
    CneApp \
    IWlanService \
    TimeService \
    QtiTelephonyService \
    imssettings \
    ims \
    qcrilmsgtunnel \
    DTVPlayer \
    DTVService \
    qcrilhook \
    android.hardware.gnss@2.1-service-qti.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    vendor.qti.gnss@4.0-service.xml \
    adpl \
    adsprpcd \
    capsense_reset \
    charge_only_mode \
    cnd \
    cnss-daemon \
    fm_qsoc_patches \
    hvdcp_opti \
    android.hardware.biometrics.fingerprint@2.1-fpcservice \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss@2.1-service-qti \
    qcrild \
    vendor.display.color@1.0-service \
    vendor.qti.hardware.perf@2.2-service \
    vendor.qti.hardware.qdutils_disp@1.0-service-qti \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    loc_launcher \
    lowi-server \
    mm-pp-dpps \
    mm-qcamera-daemon \
    netmgrd \
    pm-proxy \
    pm-service \
    port-bridge \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    rmt_storage \
    sensors.qti \
    tftp_server \
    thermal-engine \
    time_daemon \
    xtra-daemon \
    xtwifi-client \
    xtwifi-inet-agent

PRODUCT_PACKAGES += \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so \
    vendor_firmware_wlan_prima_WCNSS_qcom_wlan_nv_bin \
    vendor_firmware_wlan_prima_WCNSS_qcom_wlan_nv_Argentina_bin \
    vendor_firmware_wlan_prima_WCNSS_qcom_wlan_nv_Brazil_bin \
    vendor_firmware_wlan_prima_WCNSS_qcom_wlan_nv_India_bin \
    vendor_firmware_wlan_prima_WCNSS_qcom_wlan_nv_epa_bin \
    vendor_firmware_wlan_prima_WCNSS_wlan_dictionary_dat \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so
